services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=my_store
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5433:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - 5050:80

    mysql:
        image: mysql
        environment:
            - MYSQL_DATABASE=my_store
            - MYSQL_USER=
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PORT=3306
        ports:
            - 3309:3306
        volumes:
            - ./mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=mysql
        ports:
            - 8080:80
